import APIs.Gemini;
import APIs.OpenAI;
import Functions.ChangeToVideo;
import Functions.ChoseElement;
import Functions.Element;
import Functions.ExpandVideo;


import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.*;


public class Main {

    public static void main(String[] args) throws Exception {
        //System.out.println(System.getenv("GEMINI_API_KEY2"));
        int elements = 0;
        boolean completeSelection = false;
        Scanner scanner = new Scanner(System.in);
        String selection ;
        String extension = "";
        List<Element> elementsList = new ArrayList<>();

        while (!completeSelection){
            // Select the file to add
            File file =  ChoseElement.choseElement();


            int i = file.getName().lastIndexOf('.');
            if (i > 0) {
                extension = file.getName().substring(i + 1).toLowerCase();
            }
            System.out.println("selected : "+file.getName());
            System.out.println("extension : "+extension);

            if (extension.equals("jpg") || extension.equals("jpeg") || extension.equals("png")|| extension.equals("bmp")  || extension.equals("mp4")) {
                Element element = new Element(file, file.lastModified(), extension, file.getAbsolutePath());
                elementsList.add(element);

                System.out.println("File add: " + file.getName());
                System.out.println("Date: " + new Date(file.lastModified()));
            } else {
                System.out.println("Invalid file.");
            }

            System.out.println("You want select another file? [y/n]");
            selection = scanner.nextLine();
            if (Objects.equals(selection, "n")){
                completeSelection=true;
                scanner.close();
            }
        }

        //Sort videos by date
        elementsList.sort(Comparator.comparingLong(Element::getDate));
        System.out.println("\nFiles sorted by date:");
        int elementNumber = 0;
        for (Element element : elementsList) {

            System.out.println(element.getFile().getName() + " -> " + new Date(element.getDate()));

            if (element.getExtension().equals("jpg")||element.getExtension().equals("jpeg")||element.getExtension().equals("png")||element.getExtension().equals("bmp")) {
                ChangeToVideo.imageToVideo(element.getPath(), elementNumber);
            } else if (element.getExtension().equals("mp4")) {
                ChangeToVideo.videoToVideo(element.getPath(), elementNumber);
            }else {
                System.out.println("invalid file.");
            }
            elementNumber++;
        }

        //In this for loop the paths of each cip are added to the list of elements
        FileWriter list = new FileWriter("list.txt");
        for (int i=0; i<=elementNumber;i++){
            File clip = new File("clip_"+i+".mp4");
            list.write("file '" + clip.getAbsolutePath().replace("\\", "/") + "'\n");
        }
        list.close();



        //Finally, all the videos that are in the video list are joined.
        //n means it is the first "expansion".
        ExpandVideo.expandVideo(new File("list.txt").getAbsolutePath(),1);
        System.out.println("video_v1 finished");


        //Gemini returns me a description of the video built with the given elements.
        String description = Gemini.describeVideo("final_video.mp4");
        //System.out.println(description);

        //We create a file to save the description of Gemini
        FileWriter writer = new FileWriter("descripcion.json");
        writer.write(description);
        writer.close();



        //This variable retrieves the description from the description file.
        String content = Files.readString(Path.of("descripcion.json"));

        //These methods generate two images with AI with two different propts
        Gemini.generateImage(content,"src/support_resources/initialImage.jpg","initial");
        //OpenAI.generateImage(contenido,"src/support_resources/initialImage.jpg","initial");
        Thread.sleep(1000);
        Gemini.generateImage(content,"src/support_resources/finalImage.jpg","final");
        //OpenAI.generateImage(contenido,"src/support_resources/finalImage.jpg","final");

        //Here the phrase from the last image is generated
        String phrase = OpenAI.generatePhrase(content);


        //Video audio is generated
        OpenAI.generateSpeech(content,"speech.mp3",phrase);
        File speech = new File("speech.mp3");


        ExpandVideo.fixSpeech(speech.getAbsolutePath());
        speech = new File("speech_vfinal.mp4");


        //The 2 images generated by AI are converted into video
        File initial = new File("initialImage.jpg");
        File fin = new File("finalImage.jpg");
        ChangeToVideo.imageToVideo(initial.getAbsolutePath(), 201);
        ChangeToVideo.imageToVideoWithText(fin.getAbsolutePath(), 202,phrase);

         list = new FileWriter("finalList.txt");

        // Here the start and end image clip are added to the list.
        File clip0 = new File("clip_"+201+".mp4");
        File clip1 = new File("clip_"+202+".mp4");
        File video = new File("video_v1.mp4");
        list.write("file '" + clip0.getAbsolutePath().replace("\\", "/") + "'\n");
        list.write("file '" + video.getAbsolutePath().replace("\\", "/") + "'\n");
        list.write("file '" + clip1.getAbsolutePath().replace("\\", "/") + "'\n");
        list.close();

        //They finally come together to have the full video
        ExpandVideo.expandVideo(new File("finalList.txt").getAbsolutePath(),2);
        System.out.println("final_video finished");

        //the arranged speech and the full video are joined
        ProcessBuilder pb = new ProcessBuilder(
                "ffmpeg", "-y",
                "-i", new File("video_v2.mp4").getAbsolutePath(),
                "-i", speech.getAbsolutePath(),
                "-filter_complex", "[1:a]apad[a]",
                "-map", "0:v:0",
                "-map", "[a]",
                "-c:v", "copy",
                "-c:a", "aac",
                "-shortest",
                "video_vfinal.mp4"
        );
        pb.inheritIO();
        pb.start().waitFor();
        System.out.println("finish proses, find video_vfinal.mp4");
    }
}